"""
Title: Count Distinct Prefix-Suffix ID Matches

Problem Description:
You are given an array of lowercase strings `ids`, where each string represents a product
identifier generated by different systems. Two identifiers `a` and `b` are considered
compatible if there exists a non-empty string `x` such that `x` is both a prefix and a suffix
of `a`, and `x` is also both a prefix and a suffix of `b`. In other words, both identifiers
share at least one common non-empty border string. A border of a string is a string that is
simultaneously a prefix and a suffix of that string.

Your task is to count the number of distinct index pairs `(i, j)` with `0 <= i < j < ids.length`
such that `ids[i]` and `ids[j]` are compatible.

Constraints:
- 1 <= ids.length <= 2 * 10^5
- 1 <= ids[i].length <= 2 * 10^5
- ids[i] contains only lowercase English letters
- The sum of all ids[i].length does not exceed 2 * 10^5
- The answer may not fit in a 32-bit integer

Important observation:
A string always has itself as a border. Therefore, for any two strings s and t, if they share
at least one common border x, then x starts with the same first character in both strings.
Because x is also a suffix, x ends with the same character in both strings, and since x is a
prefix, that ending character is determined by x itself.

Most importantly, every non-empty border of a string starts with the first character of that
string. Therefore, two strings can share a border only if they have the same first character.
And if two strings have the same first character c, then the length-1 string c is always both
a prefix and a suffix exactly when the string also ends with c.

So compatibility reduces to:
Two strings are compatible if and only if they both start and end with the same character.

This turns the problem into counting, for each character 'a'..'z', how many strings have
that character as both first and last character. If a character appears in k such strings,
it contributes k * (k - 1) // 2 compatible pairs.
"""

from typing import List


class Solution:
    def count_compatible_pairs(self, ids: List[str]) -> int:
        """
        Count the number of distinct index pairs of compatible identifiers.

        A pair of strings is compatible if they share at least one common non-empty border.
        Using the key observation explained in the file header, this is equivalent to checking
        whether both strings start and end with the same character.

        Args:
            ids: List of lowercase strings.

        Returns:
            The number of distinct compatible index pairs.

        Time complexity:
            O(n), where n is the number of strings.
            We inspect only the first and last character of each string.

        Space complexity:
            O(1), because we store counts for only 26 lowercase letters.
        """
        # We will count how many strings belong to each "bucket" determined by:
        #   first character == last character == some letter c
        #
        # Why is this enough?
        # -------------------
        # Suppose two strings share a common border x.
        # - x is a prefix of both strings, so both strings must start with x[0].
        # - x is a suffix of both strings, so both strings must end with x[-1].
        # - Since x is the same string in both, x[0] and x[-1] are fixed.
        #
        # In particular, if x has length 1, then x is just one character c.
        # A string has border "c" exactly when it starts with c and ends with c.
        #
        # Now consider any shared border x of two strings. Since x is a prefix of both,
        # both strings start with x[0]. Since x is also a suffix of both, both strings end
        # with x[-1]. But because x is the same border string for both, the first and last
        # characters match across the two strings. For a common border to exist at all,
        # both strings must at least share the same first character and same last character.
        #
        # More strongly, because x is a prefix, the first character of x equals the first
        # character of the string; because x is a suffix, the last character of x equals the
        # last character of the string. Therefore, if two strings share any border x, then
        # both strings must start with the same character c and end with the same character c
        # when x has length 1. That means "c" itself is a common border.
        #
        # So counting shared borders becomes counting strings where first == last == c.
        counts: List[int] = [0] * 26

        # Process each identifier exactly once.
        for s in ids:
            # Every string is non-empty by constraint, so s[0] and s[-1] are safe.
            first_char: str = s[0]
            last_char: str = s[-1]

            # Only strings whose first and last characters are equal can contribute
            # to any compatible pair, because then the one-character string consisting
            # of that character is a border.
            if first_char == last_char:
                index: int = ord(first_char) - ord("a")
                counts[index] += 1

        # Now compute the number of pairs inside each character bucket.
        #
        # If a bucket contains k strings, then any two of them form a compatible pair.
        # Number of unordered pairs from k items is:
        #   C(k, 2) = k * (k - 1) // 2
        answer: int = 0
        for count in counts:
            answer += count * (count - 1) // 2

        return answer


if __name__ == "__main__":
    solution = Solution()

    # Sample input 1 from the prompt.
    #
    # Careful verification:
    # "ababa" starts/ends with 'a'
    # "aba" starts/ends with 'a'
    # "xxabaxx" starts/ends with 'x'
    # "abc" starts with 'a', ends with 'c' -> not eligible
    # "a" starts/ends with 'a'
    #
    # So the 'a' bucket has 3 strings: indices 0, 1, 4 -> contributes C(3,2)=3 pairs:
    # (0,1), (0,4), (1,4)
    # The 'x' bucket has 1 string -> 0 pairs
    # Total = 3
    ids1: List[str] = ["ababa", "aba", "xxabaxx", "abc", "a"]
    print(solution.count_compatible_pairs(ids1))  # Expected: 3

    # Sample input 2 from the prompt.
    #
    # "aaaa" -> starts/ends with 'a'
    # "aa" -> starts/ends with 'a'
    # "baab" -> starts/ends with 'b'
    # "aabaaa" -> starts/ends with 'a'
    # "zz" -> starts/ends with 'z'
    #
    # 'a' bucket has 3 strings -> C(3,2)=3
    # 'b' bucket has 1 -> 0
    # 'z' bucket has 1 -> 0
    # Total = 3
    ids2: List[str] = ["aaaa", "aa", "baab", "aabaaa", "zz"]
    print(solution.count_compatible_pairs(ids2))  # Expected: 3

    # Additional quick sanity checks.
    ids3: List[str] = ["abc", "def", "ghi"]
    print(solution.count_compatible_pairs(ids3))  # Expected: 0

    ids4: List[str] = ["a", "aa", "aba", "abba", "aca"]
    print(solution.count_compatible_pairs(ids4))  # Expected: 10