/*
Title: Count Distinct Prefix-Suffix ID Matches
Difficulty: Hard
Topic: Hashing

Problem Description:
You are given an array of lowercase strings ids, where each string represents a product identifier generated by different systems.
Two identifiers a and b are considered compatible if there exists a non-empty string x such that x is both a prefix and a suffix of a,
and x is also both a prefix and a suffix of b. In other words, both identifiers share at least one common non-empty border string.
A border of a string is a string that is simultaneously a prefix and a suffix of that string.

Your task is to count the number of distinct index pairs (i, j) with 0 <= i < j < ids.length such that ids[i] and ids[j] are compatible.

Because the total input size can be large, a naive comparison of every pair and every possible border will be too slow.
You need an efficient solution that uses hashing or related string-signature techniques to detect shared borders across many strings.

Return the number of compatible pairs.

Constraints:
- 1 <= ids.length <= 2 * 10^5
- 1 <= ids[i].length <= 2 * 10^5
- ids[i] contains only lowercase English letters
- The sum of all ids[i].length does not exceed 2 * 10^5
- The answer may not fit in a 32-bit integer

Important note about the examples:
The textual explanations in the prompt are inconsistent. For example, since every string is a border of itself,
two strings are compatible exactly when they share at least one common non-empty border string.
A key observation is that if two strings share any common border x, then the first character of x is also the last character of x,
so x[0] must equal x[last]. Therefore x must begin and end with the same character c.
That means both strings must have the same first and last character c.
Conversely, if two strings have the same first and last character c, then the one-character string c is a border of both strings.
So compatibility is equivalent to:
    ids[i][0] == ids[j][0] AND ids[i][^1] == ids[j][^1]
which is simply:
    first character matches and last character matches.

Therefore, the problem reduces to counting pairs of strings grouped by their (firstChar, lastChar) pair.
*/

using System;
using System.Collections.Generic;

public class Solution
{
    /*
    Time Complexity:
    O(n), where n is the number of strings.
    We inspect only the first and last character of each string once.

    Space Complexity:
    O(1) auxiliary space in practice, because there are only 26 * 26 = 676 possible
    (first character, last character) combinations for lowercase English letters.
    */
    public long CountCompatiblePairs(string[] ids)
    {
        // We will count how many strings we have already seen for each possible
        // (first character, last character) combination.
        //
        // Why this works:
        // A string has a non-empty border in common with another string if and only if
        // they share the same first and last character.
        //
        // Proof idea:
        // - If they share a border x, then x must be both prefix and suffix of each string.
        // - Since x is a border, x[0] == x[last], because x starts where the string starts
        //   and ends where the string ends.
        // - Therefore both strings must start with x[0] and end with x[last], which are equal.
        // - So both strings have the same first and last character.
        // - Conversely, if two strings have the same first and last character c,
        //   then the one-character string "c" is a prefix and suffix of both strings,
        //   so they are compatible.
        //
        // Because the alphabet is only lowercase English letters, we can store counts
        // in a fixed 26x26 array instead of a dictionary. This is simple and fast.
        long[,] count = new long[26, 26];

        // This variable stores the total number of valid pairs found so far.
        long answer = 0;

        // We process strings from left to right.
        // For the current string at index j, every previously seen string i < j
        // with the same (firstChar, lastChar) forms one valid pair (i, j).
        foreach (var s in ids)
        {
            // Each string is guaranteed to be non-empty by the constraints.
            int first = s[0] - 'a';
            int last = s[s.Length - 1] - 'a';

            // All previously seen strings with the same first/last character pair
            // are compatible with the current string.
            answer += count[first, last];

            // Now include the current string in the seen set for future strings.
            count[first, last]++;
        }

        return answer;
    }
}

// -------------------------
// Demo code
// -------------------------

var solution = new Solution();

// Example 1 from the prompt.
// Based on the actual definition, compatibility is determined by matching first and last characters.
// "ababa" -> (a,a)
// "aba"   -> (a,a)
// "xxabaxx" -> (x,x)
// "abc"   -> (a,c)
// "a"     -> (a,a)
// So the compatible pairs are among indices {0,1,4}: (0,1), (0,4), (1,4) => 3
string[] ids1 = ["ababa", "aba", "xxabaxx", "abc", "a"];
Console.WriteLine(solution.CountCompatiblePairs(ids1)); // 3

// Example 2 from the prompt.
// "aaaa"   -> (a,a)
// "aa"     -> (a,a)
// "baab"   -> (b,b)
// "aabaaa" -> (a,a)
// "zz"     -> (z,z)
// Compatible pairs among {0,1,3}: (0,1), (0,3), (1,3) => 3
string[] ids2 = ["aaaa", "aa", "baab", "aabaaa", "zz"];
Console.WriteLine(solution.CountCompatiblePairs(ids2)); // 3

// Additional quick checks
string[] ids3 = ["a"];
Console.WriteLine(solution.CountCompatiblePairs(ids3)); // 0

string[] ids4 = ["ab", "acb", "adb", "xbx", "ay"];
// (a,b), (a,b), (a,b), (x,x), (a,y)
// First three form 3 pairs
Console.WriteLine(solution.CountCompatiblePairs(ids4)); // 3