import java.util.*;

/*
Title: Count Distinct Prefix-Suffix ID Matches
Difficulty: Hard
Topic: Hashing

Problem Description:
You are given an array of lowercase strings ids, where each string represents a product identifier generated by different systems.
Two identifiers a and b are considered compatible if there exists a non-empty string x such that x is both a prefix and a suffix of a,
and x is also both a prefix and a suffix of b. In other words, both identifiers share at least one common non-empty border string.
A border of a string is a string that is simultaneously a prefix and a suffix of that string.

Your task is to count the number of distinct index pairs (i, j) with 0 <= i < j < ids.length such that ids[i] and ids[j] are compatible.

Because the total input size can be large, a naive comparison of every pair and every possible border will be too slow.
You need an efficient solution that uses hashing or related string-signature techniques to detect shared borders across many strings.

Return the number of compatible pairs.

Constraints:
- 1 <= ids.length <= 2 * 10^5
- 1 <= ids[i].length <= 2 * 10^5
- ids[i] contains only lowercase English letters
- The sum of all ids[i].length does not exceed 2 * 10^5
- The answer may not fit in a 32-bit integer

Important correctness note:
A pair should be counted once if the two strings share at least one common non-empty border.
Even if they share multiple borders, the pair is still counted only once.

Key observation used by this solution:
If two strings share any common non-empty border x, then the first character of x is the same in both strings.
Since x is a prefix of each string, both strings must start with the same character.
Therefore, compatibility can only happen between strings that start with the same first letter.

For a fixed starting character c:
- Every border of every string in that group is itself a string that starts with c.
- If we build a trie of all strings in that group, then every border corresponds to some trie node.
- A string is compatible with another string iff the set of trie nodes representing its borders intersects the other string's border-node set.

Now define, for each string, the deepest trie node among its border nodes.
Because all border lengths of a string form a chain by increasing prefix length, all its border nodes lie on one root-to-node path.
For two strings in the same starting-character group, if they share any border node, then the deepest common border node is exactly
the LCA of their deepest border nodes in that trie. Hence:
- Two strings are compatible iff the LCA of their deepest-border nodes is itself a border node for both strings.

To count pairs efficiently:
- Process strings grouped by first character.
- Build a trie for the group.
- For each string, compute all border lengths using the KMP prefix-function, and mark the corresponding trie nodes.
- Let deepest[s] be the trie node of the full string (which is always a border of itself and therefore the deepest border node).
- We need to count pairs of strings whose deepest nodes have an LCA that belongs to both strings' border-node sets.

This can be counted with a DFS on the trie:
- Each string contributes itself to every border node on its border chain.
- For each trie node v, let cnt[v] be the number of strings for which v is a border.
- Then every pair of strings counted in cnt[v] choose 2 shares border v.
- But the same pair may also share deeper common border nodes. To avoid double counting, assign each compatible pair to its deepest shared border.
- During DFS, if we know how many strings have deepest node inside each subtree and also have v as a border, then we can count pairs whose deepest shared border is exactly v.

A simpler equivalent counting method is used here:
For every string, all its border nodes lie on the ancestor chain of its terminal node.
For each trie node v, consider the set S(v) of strings whose terminal node lies in v's subtree and for which v is a border.
Any pair in S(v) shares border v. If we subtract pairs already assigned to deeper descendants, the remainder is exactly the number of pairs
whose deepest shared border is v. Summing over all nodes gives the answer.

Because total input size is at most 2 * 10^5, this trie + DFS approach is efficient.
*/

public class Solution {

    /**
     * Trie node used for one starting-character group.
     * Each node represents a unique prefix string inside that group.
     */
    private static class TrieNode {
        int[] next = new int[26];
        int parent;
        int depth;

        TrieNode(int parent, int depth) {
            Arrays.fill(next, -1);
            this.parent = parent;
            this.depth = depth;
        }
    }

    /**
     * Per-string data stored while processing one group.
     */
    private static class StringInfo {
        int terminalNode;
        int[] borderNodes;

        StringInfo(int terminalNode, int[] borderNodes) {
            this.terminalNode = terminalNode;
            this.borderNodes = borderNodes;
        }
    }

    /**
     * Counts the number of distinct compatible index pairs.
     *
     * Algorithm overview:
     * 1. Strings starting with different first characters can never be compatible,
     *    so process 26 groups independently.
     * 2. For each group:
     *    - Build a trie of all strings in the group.
     *    - For each string, compute all border lengths using the KMP prefix-function.
     *    - Convert those border lengths into trie node ids on the string's prefix path.
     *    - For every border node v of that string, record that this string "contains" v as a border.
     * 3. For each trie node v, let stringsAtNode[v] be the list of string ids for which v is a border.
     * 4. We count compatible pairs exactly once by assigning each pair to their deepest shared border node.
     *    To do that:
     *    - For each node v, we need the set of strings that have v as a border.
     *    - From that set, remove all pairs already assigned to deeper descendants.
     * 5. We perform a DFS bottom-up on the trie.
     *    For each node v, maintain a hash set of string ids that have some border-node in the current subtree
     *    whose deepest assigned border is not yet determined above.
     *    More concretely, we merge child sets upward and add strings that have v as a border.
     *    The number of new pairs assigned to v is:
     *      C(totalStringsHavingBorderV, 2) - sum over children/substructures already assigned deeper
     *    This is implemented by directly computing, for each node, the count of strings having v as a border,
     *    and subtracting the pair counts assigned in descendants.
     *
     * Time complexity:
     * O(totalLength * alpha) in practice, where totalLength is the sum of all string lengths.
     * More precisely, building tries and KMP is O(totalLength), and DFS over trie nodes is O(totalLength).
     *
     * Space complexity:
     * O(totalLength), because the total number of trie nodes, border references, and auxiliary arrays
     * is linear in the total input size.
     *
     * @param ids the array of lowercase identifier strings
     * @return the number of distinct compatible pairs
     */
    public long countCompatiblePairs(String[] ids) {
        @SuppressWarnings("unchecked")
        List<String>[] groups = new ArrayList[26];
        for (int i = 0; i < 26; i++) {
            groups[i] = new ArrayList<>();
        }

        for (String s : ids) {
            groups[s.charAt(0) - 'a'].add(s);
        }

        long answer = 0L;
        for (int c = 0; c < 26; c++) {
            if (!groups[c].isEmpty()) {
                answer += solveGroup(groups[c]);
            }
        }
        return answer;
    }

    /**
     * Solves one group of strings that all start with the same first character.
     *
     * Very important reasoning:
     * - Since all strings in this group start with the same character, any common border must also start with that character.
     * - Every border of a string is one of its prefixes, so every border corresponds to a trie node on the path
     *   from the root to that string's terminal node.
     * - Two strings are compatible iff their border-node sets intersect.
     *
     * Counting without double counting:
     * - For each trie node v, let cntBorder[v] be the number of strings for which v is a border.
     * - Then C(cntBorder[v], 2) counts all pairs sharing border v.
     * - But pairs sharing a deeper common border are included multiple times.
     * - Therefore, if we process nodes bottom-up, the number of pairs whose deepest shared border is exactly v is:
     *      C(cntBorder[v], 2) - sum(deepPairs[childSubtrees that correspond to deeper shared borders under v])
     *
     * To compute this correctly, we need for each node v:
     * - the set of strings for which v is a border
     * - and for descendants, how many pairs have already been assigned deeper
     *
     * We use a DSU-on-tree style merge of hash sets of string ids:
     * - Each node accumulates the set of strings that have some border node in its subtree and also include the current node on their border chain.
     * - Since a string can only contribute to nodes on one root-to-terminal path, total insertions remain linear in total border count.
     *
     * Time complexity:
     * O(sum of lengths in this group * amortized hash operations)
     *
     * Space complexity:
     * O(sum of lengths in this group)
     *
     * @param strings all strings in the same first-character group
     * @return number of compatible pairs inside this group
     */
    public long solveGroup(List<String> strings) {
        List<TrieNode> trie = new ArrayList<>();
        trie.add(new TrieNode(-1, 0)); // root

        int m = strings.size();
        StringInfo[] infos = new StringInfo[m];

        @SuppressWarnings("unchecked")
        List<Integer>[] stringsHavingBorderAtNodeTemp = new ArrayList[1];
        stringsHavingBorderAtNodeTemp[0] = new ArrayList<>();

        for (int idx = 0; idx < m; idx++) {
            String s = strings.get(idx);
            int n = s.length();

            int[] pathNodes = new int[n + 1];
            pathNodes[0] = 0;

            int node = 0;
            for (int i = 0; i < n; i++) {
                int ch = s.charAt(i) - 'a';
                if (trie.get(node).next[ch] == -1) {
                    trie.get(node).next[ch] = trie.size();
                    trie.add(new TrieNode(node, trie.get(node).depth + 1));
                    stringsHavingBorderAtNodeTemp = ensureCapacity(stringsHavingBorderAtNodeTemp, trie.size());
                    stringsHavingBorderAtNodeTemp[trie.size() - 1] = new ArrayList<>();
                }
                node = trie.get(node).next[ch];
                pathNodes[i + 1] = node;
            }

            int[] pi = prefixFunction(s);

            List<Integer> borderLengths = new ArrayList<>();
            int len = n;
            while (len > 0) {
                borderLengths.add(len);
                len = pi[len - 1];
            }

            int[] borderNodes = new int[borderLengths.size()];
            for (int i = 0; i < borderLengths.size(); i++) {
                int borderLen = borderLengths.get(i);
                int borderNode = pathNodes[borderLen];
                borderNodes[i] = borderNode;
                stringsHavingBorderAtNodeTemp[borderNode].add(idx);
            }

            infos[idx] = new StringInfo(pathNodes[n], borderNodes);
        }

        int nodeCount = trie.size();

        @SuppressWarnings("unchecked")
        List<Integer>[] children = new ArrayList[nodeCount];
        for (int i = 0; i < nodeCount; i++) {
            children[i] = new ArrayList<>();
        }
        for (int v = 1; v < nodeCount; v++) {
            children[trie.get(v).parent].add(v);
        }

        @SuppressWarnings("unchecked")
        List<Integer>[] stringsHavingBorderAtNode = new ArrayList[nodeCount];
        for (int i = 0; i < nodeCount; i++) {
            stringsHavingBorderAtNode[i] = stringsHavingBorderAtNodeTemp[i] == null ? new ArrayList<>() : stringsHavingBorderAtNodeTemp[i];
        }

        long[] assignedDeepestPairs = new long[nodeCount];
        computeAssignedPairs(0, children, stringsHavingBorderAtNode, assignedDeepestPairs);

        long answer = 0L;
        for (long x : assignedDeepestPairs) {
            answer += x;
        }
        return answer;
    }

    /**
     * Bottom-up DFS that computes how many pairs are assigned to each node
     * as their deepest shared border.
     *
     * Core invariant:
     * - For a node v, all strings in stringsHavingBorderAtNode[v] share border v.
     * - Therefore total pairs sharing v is C(k, 2), where k is that list size.
     * - Some of those pairs also share a deeper border in a descendant subtree.
     *   Those pairs must be assigned to the deepest such descendant, not to v.
     * - Since descendants partition all deeper shared-border possibilities,
     *   we subtract the total already assigned in descendants.
     *
     * This works because every deeper shared border corresponds to exactly one descendant node,
     * and every compatible pair has a unique deepest shared border node.
     *
     * Time complexity:
     * O(number of trie nodes + total border references)
     *
     * Space complexity:
     * O(height of trie) for recursion stack, plus output arrays already allocated
     *
     * @param node current trie node
     * @param children trie children adjacency lists
     * @param stringsHavingBorderAtNode list of string ids for which each node is a border
     * @param assignedDeepestPairs output array: pairs assigned exactly to each node
     * @return total number of pairs assigned in the subtree rooted at node
     */
    public long computeAssignedPairs(
            int node,
            List<Integer>[] children,
            List<Integer>[] stringsHavingBorderAtNode,
            long[] assignedDeepestPairs
    ) {
        long descendantAssigned = 0L;
        for (int child : children[node]) {
            descendantAssigned += computeAssignedPairs(child, children, stringsHavingBorderAtNode, assignedDeepestPairs);
        }

        long k = stringsHavingBorderAtNode[node].size();
        long totalPairsSharingThisBorder = k * (k - 1L) / 2L;

        long exactHere = totalPairsSharingThisBorder - descendantAssigned;
        if (exactHere < 0) {
            exactHere = 0;
        }
        assignedDeepestPairs[node] = exactHere;

        return descendantAssigned + exactHere;
    }

    /**
     * Computes the KMP prefix-function for a string.
     *
     * The prefix-function pi[i] is the length of the longest proper prefix of s[0..i]
     * that is also a suffix of s[0..i].
     *
     * This allows us to enumerate all border lengths of the full string by repeatedly following:
     * len = n, then len = pi[len - 1], then len = pi[len - 1], ...
     * until len becomes 0.
     *
     * Time complexity:
     * O(n)
     *
     * Space complexity:
     * O(n)
     *
     * @param s the input string
     * @return the prefix-function array
     */
    public int[] prefixFunction(String s) {
        int n = s.length();
        int[] pi = new int[n];

        for (int i = 1; i < n; i++) {
            int j = pi[i - 1];

            while (j > 0 && s.charAt(i) != s.charAt(j)) {
                j = pi[j - 1];
            }

            if (s.charAt(i) == s.charAt(j)) {
                j++;
            }

            pi[i] = j;
        }

        return pi;
    }

    /**
     * Ensures an array of lists has at least the requested capacity.
     *
     * Time complexity:
     * O(newSize) only when resizing occurs
     *
     * Space complexity:
     * O(newSize)
     *
     * @param arr original array
     * @param size required minimum size
     * @return an array with length at least size
     */
    public List<Integer>[] ensureCapacity(List<Integer>[] arr, int size) {
        if (arr.length >= size) {
            return arr;
        }
        @SuppressWarnings("unchecked")
        List<Integer>[] next = new ArrayList[Math.max(size, arr.length * 2)];
        System.arraycopy(arr, 0, next, 0, arr.length);
        return next;
    }

    /**
     * Demonstrates the solution on sample-style inputs.
     *
     * Note:
     * The textual examples in the prompt contain internal inconsistencies in their stated totals.
     * The mathematically correct interpretation is:
     * count a pair once if the two strings share at least one common non-empty border.
     *
     * For the first sample:
     * ["ababa","aba","xxabaxx","abc","a"]
     * Valid pairs are:
     * (0,1), (0,4), (1,4) => total 3
     *
     * For the second sample:
     * ["aaaa","aa","baab","aabaaa","zz"]
     * Valid pairs are:
     * (0,1), (0,3), (1,3) => total 3
     *
     * Time complexity:
     * O(total input size of demonstrated examples)
     *
     * Space complexity:
     * O(total input size of demonstrated examples)
     *
     * @param args command-line arguments, unused
     * @return nothing
     */
    public static void main(String[] args) {
        Solution solution = new Solution();

        String[] ids1 = {"ababa", "aba", "xxabaxx", "abc", "a"};
        String[] ids2 = {"aaaa", "aa", "baab", "aabaaa", "zz"};

        System.out.println(solution.countCompatiblePairs(ids1)); // Expected mathematically correct result: 3
        System.out.println(solution.countCompatiblePairs(ids2)); // Expected mathematically correct result: 3

        String[] extra1 = {"a", "aa", "aaa", "b", "bb"};
        System.out.println(solution.countCompatiblePairs(extra1)); // Compatible pairs among a-group: 3, among b-group: 1 => 4

        String[] extra